name: Pull Request Stylecheck

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.14.1
      with:
        reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
