name: Push Stylecheck

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Run Flake8
      uses: suo/flake8-github-action@v1
      with:
        checkName: 'build'   # NOTE: this needs to be the same as the job name
        reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
