name: Push Stylecheck

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: Run Flake8
      uses: suo/flake8-github-action@v1
